export { swaggerBussSignup } from  './auth/business/sign-up';
export { swaggerBussLogin } from  './auth/business/login';
export { swaggerUserSignUp } from './auth/sign-up';
export { swaggerUserLogin } from './auth/login';
export { swaggerUserLogout } from './auth/logout';
export { swaggerCallback } from './auth/callback';
export { swaggerOAuth } from './auth/oauth';
export { swaggerProfileGetAll } from './profile/get';
export { swaggerProfileUpdate } from './profile/update';
export { swaggerStorageImgUpload } from './storage/upload-image/create';
export { swaggerStorageVideoUpload } from './storage/upload-video/create';
export { swaggerDestCreate } from './destination/create';
export { swaggerDestGet } from './destination/get';
export { swaggerDestGetAll } from './destination/get-all';
export { swaggerDesChildrenGet } from './destination/children/get';
export { swaggerDesDetailsGet } from './destination/details/get';
export { swaggerDesIconicPhotosGet } from './destination/iconic_photos/get';
export { swaggerAttractionGet } from './destination/attractions/get';
export { swaggerChannelCreate } from './channel/create';
export { swaggerChannelGetAll } from './channel/get-all';
export { swaggerChannelUpdate } from './channel/update';
export { swaggerStoryGenerate } from './story/generate/create';
export { swaggerStoryCreate } from './story/create';
export { swaggerStoryGetAll } from './story/get-all';
export { swaggerStoryGet } from './story/get';
export { swaggerStoryUpdate } from './story/update';
export { swaggerStoryDel } from './story/delete';
export { swaggerPublicStoryGetAll } from './story/public/get-all';
export { swaggerPublicStoryGet } from './story/public/get';
export { swaggerDestUpdate } from './destination/update';
export { swaggerDestDetailsCreate } from './destination/details/create';
export { swaggerSearchAgent } from './agents/search/create';
// export { swaggerBussCreate } from './challenge/business/create';
// export { swaggerBussGetAll } from './challenge/business/get-all';
// export { swaggerBussDel } from './challenge/business/delete';
// export { swaggerBussUpdate } from './challenge/business/update';
// export { swaggerUserGetAll } from './challenge/user/get-all';
// export { swaggerUserGet } from './challenge/user/get';
