export { swaggerBussSignup } from  './auth/business/sign-up';
export { swaggerBussLogin } from  './auth/business/login';
export { swaggerUserSignUp } from './auth/sign-up';
export { swaggerUserLogin } from './auth/login';
export { swaggerUserLogout } from './auth/logout';
export { swaggerCallback } from './auth/callback';
export { swaggerOAuth } from './auth/oauth';
export { swaggerProfileGet } from './profile/get';
export { swaggerProfileUpdate } from './profile/update';
export { swaggerProfileAvatarUpdate } from './profile/avatar/update';
export { swaggerBusinessProfileGet } from './profile/business/get';
export { swaggerBusinessProfileGetAll } from './profile/business/get-all';
export { swaggerBusinessProfileUpdate } from './profile/business/update';
export { swaggerStorageImgUpload } from './storage/upload-image/create';
export { swaggerStorageVideoUpload } from './storage/upload-video/create';
// export { swaggerDestCreate } from './destination/create';
// export { swaggerDestGet } from './destination/get';
// export { swaggerDestGetAll } from './destination/get-all';
// export { swaggerDestUpdate } from './destination/update';
// export { swaggerDesChildrenGet } from './destination/children/get';
// export { swaggerDesDetailsGet } from './destination/details/get';
// export { swaggerDestDetailsCreate } from './destination/details/create';
// export { swaggerDesIconicPhotosGet } from './destination/iconicPhotos/get';
// export { swaggerAttractionGet } from './destination/attractions/get';
export { swaggerChannelCreate } from './channel/create';
export { swaggerChannelGetAll } from './channel/get-all';
export { swaggerChannelUpdate } from './channel/update';
export { swaggerStoryGenerate } from './story/generate/create';
export { swaggerStoryCreate } from './story/create';
export { swaggerStoryGetAll } from './story/get-all';
export { swaggerStoryGet } from './story/get';
export { swaggerStoryUpdate } from './story/update';
export { swaggerStoryDel } from './story/delete';
export { swaggerPublicStoryGetAll } from './story/public/get-all';
export { swaggerPublicStoryGet } from './story/public/get';
export { swaggerSearchAgent } from './agents/search/create';
// export { swaggerBussChallengeCreate } from './destination/challenge/business/create';
// export { swaggerBussChallengeGetAll } from './destination/challenge/business/get-all';
// export { swaggerBussChallengeDel } from './destination/challenge/business/delete';
// export { swaggerBussChallengeUpdate } from './destination/challenge/business/update';
// export { swaggerUserChallengeGetAll } from './destination/challenge/user/get-all';
// export { swaggerUserChallengeGet } from './destination/challenge/user/get';
// export { swaggerBussRewardCreate } from './destination/challenge/business/reward/create';
// export { swaggerBussRewardGetAll } from './destination/challenge/business/reward/get-all';
// export { swaggerBussRewardDel } from './destination/challenge/business/reward/delete';
// export { swaggerBussRewardUpdate } from './destination/challenge/business/reward/update';
// export { swaggerUserRewardGetAll } from './destination/challenge/user/reward/get-all';
// export { swaggerUserRewardGet } from './destination/challenge/user/reward/get';

export { swaggerExpCreate } from './experiences/create';
export { swaggerExpUpdate } from './experiences/update';
export { swaggerExpDetailsCreate } from './experiences/details/create';
export { swaggerExpGet } from './experiences/get';
export { swaggerExpGetAll } from './experiences/get-all';
export { swaggerExpChildrenGet } from './experiences/children/get';
export { swaggerExpDetailsGet } from './experiences/details/get';
export { swaggerExpIconicPhotosGet } from './experiences/iconicPhotos/get';
export { swaggerLocationGet } from './experiences/locations/get';
export { swaggerPublicExpGet } from './experiences/public/get';
export { swaggerPublicExpGetAll } from './experiences/public/get-all';
export { swaggerPublicExpDetailsGet } from './experiences/public/details/get';
export { swaggerPublicExpIconicPhotosGet } from './experiences/public/iconicPhotos/get';
export { swaggerPublicLocationGet } from './experiences/public/locations/get';
export { swaggerBussChallengeCreate } from './experiences/challenge/business/create';
export { swaggerBussChallengeGetAll } from './experiences/challenge/business/get-all';
export { swaggerBussChallengeDel } from './experiences/challenge/business/delete';
export { swaggerBussChallengeUpdate } from './experiences/challenge/business/update';
export { swaggerUserChallengeGetAll } from './experiences/challenge/user/get-all';
export { swaggerUserChallengeGet } from './experiences/challenge/user/get';
export { swaggerBussRewardCreate } from './experiences/challenge/business/reward/create';
export { swaggerBussRewardGetAll } from './experiences/challenge/business/reward/get-all';
export { swaggerBussRewardDel } from './experiences/challenge/business/reward/delete';
export { swaggerBussRewardUpdate } from './experiences/challenge/business/reward/update';
export { swaggerUserRewardGetAll } from './experiences/challenge/user/reward/get-all';
export { swaggerUserRewardGet } from './experiences/challenge/user/reward/get';
export { swaggerBusinessLocationCreate } from './locations/create';
export { swaggerBusinessLocationGet } from './locations/get';
export { swaggerBusinessLocationUpdate } from './locations/update';
export { swaggerDestLocationLink } from './experiences/locations/create';
